// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "Calculateur.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



::CORBA::Exception::insertExceptionToAny CalculApp::DivisionParZero::insertToAnyFn = 0;
::CORBA::Exception::insertExceptionToAnyNCP CalculApp::DivisionParZero::insertToAnyFnNCP = 0;

CalculApp::DivisionParZero::DivisionParZero(const CalculApp::DivisionParZero& _s) : ::CORBA::UserException(_s)
{
  message = _s.message;

}

CalculApp::DivisionParZero::DivisionParZero(const char* _message)
{
  pd_insertToAnyFn    = CalculApp::DivisionParZero::insertToAnyFn;
  pd_insertToAnyFnNCP = CalculApp::DivisionParZero::insertToAnyFnNCP;
  message = _message;

}



CalculApp::DivisionParZero& CalculApp::DivisionParZero::operator=(const CalculApp::DivisionParZero& _s)
{
  if (&_s != this) {
    ((::CORBA::UserException*) this)->operator=(_s);
    message = _s.message;

  }
  return *this;
}

CalculApp::DivisionParZero::~DivisionParZero() {}

void CalculApp::DivisionParZero::_raise() const { throw *this; }

const char* CalculApp::DivisionParZero::_PD_repoId = "IDL:CalculApp/DivisionParZero:1.0";
const char* CalculApp::DivisionParZero::_PD_typeId = "Exception/UserException/CalculApp::DivisionParZero";

CalculApp::DivisionParZero* CalculApp::DivisionParZero::_downcast(::CORBA::Exception* _e) {
  return (DivisionParZero*) _NP_is_a(_e, _PD_typeId);
}

const CalculApp::DivisionParZero* CalculApp::DivisionParZero::_downcast(const ::CORBA::Exception* _e) {
  return (const DivisionParZero*) _NP_is_a(_e, _PD_typeId);
}

::CORBA::Exception* CalculApp::DivisionParZero::_NP_duplicate() const {
  return new DivisionParZero(*this);
}

const char* CalculApp::DivisionParZero::_NP_typeId() const {
  return _PD_typeId;
}

const char* CalculApp::DivisionParZero::_NP_repoId(int* _size) const {
  *_size = sizeof("IDL:CalculApp/DivisionParZero:1.0");
  return _PD_repoId;
}
 
void CalculApp::DivisionParZero::_NP_marshal(cdrStream& _s) const {
  *this >>= _s;
}

void
CalculApp::DivisionParZero::operator>>= (cdrStream& _n) const
{
  _n.marshalString(message,0);

}

void
CalculApp::DivisionParZero::operator<<= (cdrStream& _n)
{
  message = _n.unmarshalString(0);

}

void
CalculApp::Operation::operator>>= (cdrStream &_n) const
{
  nombreA >>= _n;
  nombreB >>= _n;
  _n.marshalString(typeOperation,0);

}

void
CalculApp::Operation::operator<<= (cdrStream &_n)
{
  (::CORBA::Double&)nombreA <<= _n;
  (::CORBA::Double&)nombreB <<= _n;
  typeOperation = _n.unmarshalString(0);

}

CalculApp::Calculateur_ptr CalculApp::Calculateur_Helper::_nil() {
  return ::CalculApp::Calculateur::_nil();
}

::CORBA::Boolean CalculApp::Calculateur_Helper::is_nil(::CalculApp::Calculateur_ptr p) {
  return ::CORBA::is_nil(p);

}

void CalculApp::Calculateur_Helper::release(::CalculApp::Calculateur_ptr p) {
  ::CORBA::release(p);
}

void CalculApp::Calculateur_Helper::marshalObjRef(::CalculApp::Calculateur_ptr obj, cdrStream& s) {
  ::CalculApp::Calculateur::_marshalObjRef(obj, s);
}

CalculApp::Calculateur_ptr CalculApp::Calculateur_Helper::unmarshalObjRef(cdrStream& s) {
  return ::CalculApp::Calculateur::_unmarshalObjRef(s);
}

void CalculApp::Calculateur_Helper::duplicate(::CalculApp::Calculateur_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

CalculApp::Calculateur_ptr
CalculApp::Calculateur::_duplicate(::CalculApp::Calculateur_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

CalculApp::Calculateur_ptr
CalculApp::Calculateur::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


CalculApp::Calculateur_ptr
CalculApp::Calculateur::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

CalculApp::Calculateur_ptr
CalculApp::Calculateur::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Calculateur _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Calculateur* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Calculateur;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* CalculApp::Calculateur::_PD_repoId = "IDL:CalculApp/Calculateur:1.0";


CalculApp::_objref_Calculateur::~_objref_Calculateur() {
  
}


CalculApp::_objref_Calculateur::_objref_Calculateur(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::CalculApp::Calculateur::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
CalculApp::_objref_Calculateur::_ptrToObjRef(const char* id)
{
  if (id == ::CalculApp::Calculateur::_PD_repoId)
    return (::CalculApp::Calculateur_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::CalculApp::Calculateur::_PD_repoId))
    return (::CalculApp::Calculateur_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for CalculApp::Calculateur::ajouter

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_cdouble_i_cdouble
class _0RL_cd_40d2ec45f3950023_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40d2ec45f3950023_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::Double result;
};

void _0RL_cd_40d2ec45f3950023_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_40d2ec45f3950023_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;
  (::CORBA::Double&)arg_1 <<= _n;

}

void _0RL_cd_40d2ec45f3950023_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40d2ec45f3950023_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_40d2ec45f3950023_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40d2ec45f3950023_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40d2ec45f3950023_00000000* tcd = (_0RL_cd_40d2ec45f3950023_00000000*)cd;
  CalculApp::_impl_Calculateur* impl = (CalculApp::_impl_Calculateur*) svnt->_ptrToInterface(CalculApp::Calculateur::_PD_repoId);
  tcd->result = impl->ajouter(tcd->arg_0, tcd->arg_1);


}

::CORBA::Double CalculApp::_objref_Calculateur::ajouter(::CORBA::Double a, ::CORBA::Double b)
{
  _0RL_cd_40d2ec45f3950023_00000000 _call_desc(_0RL_lcfn_40d2ec45f3950023_10000000, "ajouter", 8);
  _call_desc.arg_0 = a;
  _call_desc.arg_1 = b;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for CalculApp::Calculateur::soustraire

// Local call call-back function.
static void
_0RL_lcfn_40d2ec45f3950023_20000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40d2ec45f3950023_00000000* tcd = (_0RL_cd_40d2ec45f3950023_00000000*)cd;
  CalculApp::_impl_Calculateur* impl = (CalculApp::_impl_Calculateur*) svnt->_ptrToInterface(CalculApp::Calculateur::_PD_repoId);
  tcd->result = impl->soustraire(tcd->arg_0, tcd->arg_1);


}

::CORBA::Double CalculApp::_objref_Calculateur::soustraire(::CORBA::Double a, ::CORBA::Double b)
{
  _0RL_cd_40d2ec45f3950023_00000000 _call_desc(_0RL_lcfn_40d2ec45f3950023_20000000, "soustraire", 11);
  _call_desc.arg_0 = a;
  _call_desc.arg_1 = b;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for CalculApp::Calculateur::division

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_cdouble_i_cdouble_e_cCalculApp_mDivisionParZero
class _0RL_cd_40d2ec45f3950023_30000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40d2ec45f3950023_30000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::Double result;
};

void _0RL_cd_40d2ec45f3950023_30000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_40d2ec45f3950023_30000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;
  (::CORBA::Double&)arg_1 <<= _n;

}

void _0RL_cd_40d2ec45f3950023_30000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40d2ec45f3950023_30000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_40d2ec45f3950023_30000000::_user_exns[] = {
  CalculApp::DivisionParZero::_PD_repoId
};

void _0RL_cd_40d2ec45f3950023_30000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, CalculApp::DivisionParZero::_PD_repoId)) {
    CalculApp::DivisionParZero _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_40d2ec45f3950023_40000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40d2ec45f3950023_30000000* tcd = (_0RL_cd_40d2ec45f3950023_30000000*)cd;
  CalculApp::_impl_Calculateur* impl = (CalculApp::_impl_Calculateur*) svnt->_ptrToInterface(CalculApp::Calculateur::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->division(tcd->arg_0, tcd->arg_1);
#else
  if (!cd->is_upcall())
    tcd->result = impl->division(tcd->arg_0, tcd->arg_1);
  else {
    try {
      tcd->result = impl->division(tcd->arg_0, tcd->arg_1);
    }
    catch(CalculApp::DivisionParZero& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

::CORBA::Double CalculApp::_objref_Calculateur::division(::CORBA::Double a, ::CORBA::Double b)
{
  _0RL_cd_40d2ec45f3950023_30000000 _call_desc(_0RL_lcfn_40d2ec45f3950023_40000000, "division", 9);
  _call_desc.arg_0 = a;
  _call_desc.arg_1 = b;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for CalculApp::Calculateur::calculer

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_cCalculApp_mOperation_e_cCalculApp_mDivisionParZero
class _0RL_cd_40d2ec45f3950023_50000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40d2ec45f3950023_50000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  CalculApp::Operation_var arg_0_;
  const CalculApp::Operation* arg_0;
  ::CORBA::Double result;
};

void _0RL_cd_40d2ec45f3950023_50000000::marshalArguments(cdrStream& _n)
{
  (const CalculApp::Operation&) *arg_0 >>= _n;

}

void _0RL_cd_40d2ec45f3950023_50000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new CalculApp::Operation;
  (CalculApp::Operation&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_40d2ec45f3950023_50000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40d2ec45f3950023_50000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_40d2ec45f3950023_50000000::_user_exns[] = {
  CalculApp::DivisionParZero::_PD_repoId
};

void _0RL_cd_40d2ec45f3950023_50000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, CalculApp::DivisionParZero::_PD_repoId)) {
    CalculApp::DivisionParZero _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_40d2ec45f3950023_60000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40d2ec45f3950023_50000000* tcd = (_0RL_cd_40d2ec45f3950023_50000000*)cd;
  CalculApp::_impl_Calculateur* impl = (CalculApp::_impl_Calculateur*) svnt->_ptrToInterface(CalculApp::Calculateur::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->calculer(*tcd->arg_0);
#else
  if (!cd->is_upcall())
    tcd->result = impl->calculer(*tcd->arg_0);
  else {
    try {
      tcd->result = impl->calculer(*tcd->arg_0);
    }
    catch(CalculApp::DivisionParZero& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

::CORBA::Double CalculApp::_objref_Calculateur::calculer(const ::CalculApp::Operation& op)
{
  _0RL_cd_40d2ec45f3950023_50000000 _call_desc(_0RL_lcfn_40d2ec45f3950023_60000000, "calculer", 9);
  _call_desc.arg_0 = &(::CalculApp::Operation&) op;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for CalculApp::Calculateur::calculerMoyenne

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_cCalculApp_mTableauDeDoubles
class _0RL_cd_40d2ec45f3950023_70000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40d2ec45f3950023_70000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  CalculApp::TableauDeDoubles_var arg_0_;
  const CalculApp::TableauDeDoubles* arg_0;
  ::CORBA::Double result;
};

void _0RL_cd_40d2ec45f3950023_70000000::marshalArguments(cdrStream& _n)
{
  (const CalculApp::TableauDeDoubles&) *arg_0 >>= _n;

}

void _0RL_cd_40d2ec45f3950023_70000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new CalculApp::TableauDeDoubles;
  (CalculApp::TableauDeDoubles&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_40d2ec45f3950023_70000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40d2ec45f3950023_70000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_40d2ec45f3950023_70000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40d2ec45f3950023_80000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40d2ec45f3950023_70000000* tcd = (_0RL_cd_40d2ec45f3950023_70000000*)cd;
  CalculApp::_impl_Calculateur* impl = (CalculApp::_impl_Calculateur*) svnt->_ptrToInterface(CalculApp::Calculateur::_PD_repoId);
  tcd->result = impl->calculerMoyenne(*tcd->arg_0);


}

::CORBA::Double CalculApp::_objref_Calculateur::calculerMoyenne(const ::CalculApp::TableauDeDoubles& nombres)
{
  _0RL_cd_40d2ec45f3950023_70000000 _call_desc(_0RL_lcfn_40d2ec45f3950023_80000000, "calculerMoyenne", 16);
  _call_desc.arg_0 = &(::CalculApp::TableauDeDoubles&) nombres;

  _invoke(_call_desc);
  return _call_desc.result;


}

CalculApp::_pof_Calculateur::~_pof_Calculateur() {}


omniObjRef*
CalculApp::_pof_Calculateur::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::CalculApp::_objref_Calculateur(ior, id);
}


::CORBA::Boolean
CalculApp::_pof_Calculateur::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::CalculApp::Calculateur::_PD_repoId))
    return 1;
  
  return 0;
}

const CalculApp::_pof_Calculateur _the_pof_CalculApp_mCalculateur;

CalculApp::_impl_Calculateur::~_impl_Calculateur() {}


::CORBA::Boolean
CalculApp::_impl_Calculateur::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "ajouter")) {

    _0RL_cd_40d2ec45f3950023_00000000 _call_desc(_0RL_lcfn_40d2ec45f3950023_10000000, "ajouter", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "soustraire")) {

    _0RL_cd_40d2ec45f3950023_00000000 _call_desc(_0RL_lcfn_40d2ec45f3950023_20000000, "soustraire", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "division")) {

    _0RL_cd_40d2ec45f3950023_30000000 _call_desc(_0RL_lcfn_40d2ec45f3950023_40000000, "division", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "calculer")) {

    _0RL_cd_40d2ec45f3950023_50000000 _call_desc(_0RL_lcfn_40d2ec45f3950023_60000000, "calculer", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "calculerMoyenne")) {

    _0RL_cd_40d2ec45f3950023_70000000 _call_desc(_0RL_lcfn_40d2ec45f3950023_80000000, "calculerMoyenne", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
CalculApp::_impl_Calculateur::_ptrToInterface(const char* id)
{
  if (id == ::CalculApp::Calculateur::_PD_repoId)
    return (::CalculApp::_impl_Calculateur*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::CalculApp::Calculateur::_PD_repoId))
    return (::CalculApp::_impl_Calculateur*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
CalculApp::_impl_Calculateur::_mostDerivedRepoId()
{
  return ::CalculApp::Calculateur::_PD_repoId;
}

POA_CalculApp::Calculateur::~Calculateur() {}

