package CalculApp;


/**
* CalculApp/CalculateurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* vendredi 25 septembre 2026 09 h 14 EAT
*/


// definit les methodes accessibles a distance
public interface CalculateurOperations 
{

  // in indique que les parametres sont envoyes en entree vers le serveur
  double ajouter (double a, double b);
} // interface CalculateurOperations
