package CalculApp;


/**
* CalculApp/CalculateurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* samedi 26 septembre 2026 16 h 31 EAT
*/


// definit les methodes accessibles a distance
public interface CalculateurOperations 
{

  // in indique que les parametres sont envoyes en entree vers le serveur
  double ajouter (double a, double b);
  double soustraire (double a, double b);
  double division (double a, double b) throws CalculApp.DivisionParZero;
  double calculer (CalculApp.Operation op) throws CalculApp.DivisionParZero;
  double calculerMoyenne (double[] nombres);
} // interface CalculateurOperations
