package CalculApp;

/**
* CalculApp/CalculateurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* samedi 26 septembre 2026 15 h 43 EAT
*/


// definit les methodes accessibles a distance
public final class CalculateurHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculApp.Calculateur value = null;

  public CalculateurHolder ()
  {
  }

  public CalculateurHolder (CalculApp.Calculateur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculApp.CalculateurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculApp.CalculateurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculApp.CalculateurHelper.type ();
  }

}
