package CalculApp;


/**
* CalculApp/Calculateur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* samedi 26 septembre 2026 16 h 31 EAT
*/


// definit les methodes accessibles a distance
public interface Calculateur extends CalculateurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculateur
