package CalculApp;


/**
* CalculApp/Calculateur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* vendredi 25 septembre 2026 09 h 14 EAT
*/


// definit les methodes accessibles a distance
public interface Calculateur extends CalculateurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculateur
