package CalculApp;


/**
* CalculApp/CalculateurHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* samedi 26 septembre 2026 15 h 43 EAT
*/


// definit les methodes accessibles a distance
abstract public class CalculateurHelper
{
  private static String  _id = "IDL:CalculApp/Calculateur:1.0";

  public static void insert (org.omg.CORBA.Any a, CalculApp.Calculateur that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CalculApp.Calculateur extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CalculApp.CalculateurHelper.id (), "Calculateur");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CalculApp.Calculateur read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalculateurStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CalculApp.Calculateur value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CalculApp.Calculateur narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CalculApp.Calculateur)
      return (CalculApp.Calculateur)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CalculApp._CalculateurStub stub = new CalculApp._CalculateurStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CalculApp.Calculateur unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CalculApp.Calculateur)
      return (CalculApp.Calculateur)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CalculApp._CalculateurStub stub = new CalculApp._CalculateurStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
