package CalculApp;


/**
* CalculApp/DivisionParZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* samedi 26 septembre 2026 16 h 22 EAT
*/

public final class DivisionParZero extends org.omg.CORBA.UserException
{
  public String message = null;

  public DivisionParZero ()
  {
    super(DivisionParZeroHelper.id());
  } // ctor

  public DivisionParZero (String _message)
  {
    super(DivisionParZeroHelper.id());
    message = _message;
  } // ctor


  public DivisionParZero (String $reason, String _message)
  {
    super(DivisionParZeroHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class DivisionParZero
