package CalculApp;

/**
* CalculApp/DivisionParZeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* samedi 26 septembre 2026 16 h 22 EAT
*/

public final class DivisionParZeroHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculApp.DivisionParZero value = null;

  public DivisionParZeroHolder ()
  {
  }

  public DivisionParZeroHolder (CalculApp.DivisionParZero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculApp.DivisionParZeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculApp.DivisionParZeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculApp.DivisionParZeroHelper.type ();
  }

}
