package CalculApp;

/**
* CalculApp/OperationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* samedi 26 septembre 2026 16 h 31 EAT
*/

public final class OperationHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculApp.Operation value = null;

  public OperationHolder ()
  {
  }

  public OperationHolder (CalculApp.Operation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculApp.OperationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculApp.OperationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculApp.OperationHelper.type ();
  }

}
