package CalculApp;


/**
* CalculApp/Operation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* samedi 26 septembre 2026 16 h 31 EAT
*/

public final class Operation implements org.omg.CORBA.portable.IDLEntity
{
  public double nombreA = (double)0;
  public double nombreB = (double)0;
  public String typeOperation = null;

  public Operation ()
  {
  } // ctor

  public Operation (double _nombreA, double _nombreB, String _typeOperation)
  {
    nombreA = _nombreA;
    nombreB = _nombreB;
    typeOperation = _typeOperation;
  } // ctor

} // class Operation
