package CalculApp;


/**
* CalculApp/TableauDeDoublesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculateur.idl
* samedi 26 septembre 2026 16 h 31 EAT
*/


//  Définition du type "TableauDeDoubles"
public final class TableauDeDoublesHolder implements org.omg.CORBA.portable.Streamable
{
  public double value[] = null;

  public TableauDeDoublesHolder ()
  {
  }

  public TableauDeDoublesHolder (double[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculApp.TableauDeDoublesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculApp.TableauDeDoublesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculApp.TableauDeDoublesHelper.type ();
  }

}
