// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __Calculateur_hh__
#define __Calculateur_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_Calculateur
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_Calculateur
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_Calculateur
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CalculApp

_CORBA_MODULE_BEG

  class DivisionParZero : public ::CORBA::UserException {
  public:
    
    ::CORBA::String_member message;

  

    inline DivisionParZero() {
      pd_insertToAnyFn    = insertToAnyFn;
      pd_insertToAnyFnNCP = insertToAnyFnNCP;
    }
    DivisionParZero(const DivisionParZero&);
    DivisionParZero(const char* i_message);
    DivisionParZero& operator=(const DivisionParZero&);
    virtual ~DivisionParZero();
    virtual void _raise() const;
    static DivisionParZero* _downcast(::CORBA::Exception*);
    static const DivisionParZero* _downcast(const ::CORBA::Exception*);
    static inline DivisionParZero* _narrow(::CORBA::Exception* _e) {
      return _downcast(_e);
    }
    
    void operator>>=(cdrStream&) const ;
    void operator<<=(cdrStream&) ;

    static _core_attr insertExceptionToAny    insertToAnyFn;
    static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

    virtual ::CORBA::Exception* _NP_duplicate() const;

    static _core_attr const char* _PD_repoId;
    static _core_attr const char* _PD_typeId;

  private:
    virtual const char* _NP_typeId() const;
    virtual const char* _NP_repoId(int*) const;
    virtual void _NP_marshal(cdrStream&) const;
  };

  struct Operation {
    typedef _CORBA_ConstrType_Variable_Var<Operation> _var_type;

    
    ::CORBA::Double nombreA;

    ::CORBA::Double nombreB;

    ::CORBA::String_member typeOperation;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef Operation::_var_type Operation_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< Operation,Operation_var > Operation_out;

  class TableauDeDoubles_var;

  class TableauDeDoubles : public _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 >  {
  public:
    typedef TableauDeDoubles_var _var_type;
    inline TableauDeDoubles() {}
    inline TableauDeDoubles(const TableauDeDoubles& _s)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > (_s) {}

    inline TableauDeDoubles(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > (_max) {}
    inline TableauDeDoubles(_CORBA_ULong _max, _CORBA_ULong _len, ::CORBA::Double* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > (_max, _len, _val, _rel) {}

  

    inline TableauDeDoubles& operator = (const TableauDeDoubles& _s) {
      _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Double, 8, 8 > ::operator=(_s);
      return *this;
    }
  };

  class TableauDeDoubles_out;

  class TableauDeDoubles_var {
  public:
    inline TableauDeDoubles_var() : _pd_seq(0) {}
    inline TableauDeDoubles_var(TableauDeDoubles* _s) : _pd_seq(_s) {}
    inline TableauDeDoubles_var(const TableauDeDoubles_var& _s) {
      if (_s._pd_seq)  _pd_seq = new TableauDeDoubles(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~TableauDeDoubles_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline TableauDeDoubles_var& operator = (TableauDeDoubles* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline TableauDeDoubles_var& operator = (const TableauDeDoubles_var& _s) {
      if (&_s != this) {
        if (_s._pd_seq) {
          if (!_pd_seq)  _pd_seq = new TableauDeDoubles;
          *_pd_seq = *_s._pd_seq;
        }
        else if (_pd_seq) {
          delete _pd_seq;
          _pd_seq = 0;
        }
      }
      return *this;
    }
    inline ::CORBA::Double& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline TableauDeDoubles* operator -> () { return _pd_seq; }
    inline const TableauDeDoubles* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator TableauDeDoubles& () const { return *_pd_seq; }
#else
    inline operator const TableauDeDoubles& () const { return *_pd_seq; }
    inline operator TableauDeDoubles& () { return *_pd_seq; }
#endif
      
    inline const TableauDeDoubles& in() const { return *_pd_seq; }
    inline TableauDeDoubles&       inout()    { return *_pd_seq; }
    inline TableauDeDoubles*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline TableauDeDoubles* _retn() { TableauDeDoubles* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class TableauDeDoubles_out;
    
  private:
    TableauDeDoubles* _pd_seq;
  };

  class TableauDeDoubles_out {
  public:
    inline TableauDeDoubles_out(TableauDeDoubles*& _s) : _data(_s) { _data = 0; }
    inline TableauDeDoubles_out(TableauDeDoubles_var& _s)
      : _data(_s._pd_seq) { _s = (TableauDeDoubles*) 0; }
    inline TableauDeDoubles_out(const TableauDeDoubles_out& _s) : _data(_s._data) {}
    inline TableauDeDoubles_out& operator = (const TableauDeDoubles_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline TableauDeDoubles_out& operator = (TableauDeDoubles* _s) {
      _data = _s;
      return *this;
    }
    inline operator TableauDeDoubles*&()  { return _data; }
    inline TableauDeDoubles*& ptr()       { return _data; }
    inline TableauDeDoubles* operator->() { return _data; }

    inline ::CORBA::Double& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    TableauDeDoubles*& _data;

  private:
    TableauDeDoubles_out();
    TableauDeDoubles_out& operator=(const TableauDeDoubles_var&);
  };

#ifndef __CalculApp_mCalculateur__
#define __CalculApp_mCalculateur__
  class Calculateur;
  class _objref_Calculateur;
  class _impl_Calculateur;
  
  typedef _objref_Calculateur* Calculateur_ptr;
  typedef Calculateur_ptr CalculateurRef;

  class Calculateur_Helper {
  public:
    typedef Calculateur_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Calculateur, Calculateur_Helper> Calculateur_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Calculateur,Calculateur_Helper > Calculateur_out;

#endif

  // interface Calculateur
  class Calculateur {
  public:
    // Declarations for this interface type.
    typedef Calculateur_ptr _ptr_type;
    typedef Calculateur_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Calculateur :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Double ajouter(::CORBA::Double a, ::CORBA::Double b);
    ::CORBA::Double soustraire(::CORBA::Double a, ::CORBA::Double b);
    ::CORBA::Double division(::CORBA::Double a, ::CORBA::Double b);
    ::CORBA::Double calculer(const ::CalculApp::Operation& op);
    ::CORBA::Double calculerMoyenne(const ::CalculApp::TableauDeDoubles& nombres);

    // Constructors
    inline _objref_Calculateur()  { _PR_setobj(0); }  // nil
    _objref_Calculateur(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Calculateur();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Calculateur(const _objref_Calculateur&);
    _objref_Calculateur& operator = (const _objref_Calculateur&);
    // not implemented

    friend class Calculateur;
  };

  class _pof_Calculateur : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Calculateur() : _OMNI_NS(proxyObjectFactory)(Calculateur::_PD_repoId) {}
    virtual ~_pof_Calculateur();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Calculateur :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Calculateur();

    virtual ::CORBA::Double ajouter(::CORBA::Double a, ::CORBA::Double b) = 0;
    virtual ::CORBA::Double soustraire(::CORBA::Double a, ::CORBA::Double b) = 0;
    virtual ::CORBA::Double division(::CORBA::Double a, ::CORBA::Double b) = 0;
    virtual ::CORBA::Double calculer(const ::CalculApp::Operation& op) = 0;
    virtual ::CORBA::Double calculerMoyenne(const ::CalculApp::TableauDeDoubles& nombres) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_CalculApp
_CORBA_MODULE_BEG

  class Calculateur :
    public virtual CalculApp::_impl_Calculateur,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Calculateur();

    inline ::CalculApp::Calculateur_ptr _this() {
      return (::CalculApp::Calculateur_ptr) _do_this(::CalculApp::Calculateur::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CalculApp
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
CalculApp::Calculateur::_marshalObjRef(::CalculApp::Calculateur_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_Calculateur
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_Calculateur
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_Calculateur
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_Calculateur
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_Calculateur
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_Calculateur
#endif

#endif  // __Calculateur_hh__

